export const provinceOptions: Array<{ value: string, label: string }> = [
    { value: 'Jakarta Utara', label: 'Jakarta Utara' },
    { value: 'Jakarta Pusat', label: 'Jakarta Pusat' },
    { value: 'Jakarta Selatan', label: 'Jakarta Selatan' },
    { value: 'Jakarta Timur', label: 'Jakarta Timur' },
    { value: 'Jakarta Barat', label: 'Jakarta Barat' },
    { value: 'Tangerang', label: 'Tangerang' },
    { value: 'Tangerang Selatan', label: 'Tangerang Selatan' },
    { value: 'Bekasi', label: 'Bekasi' },
    { value: 'Aceh', label: 'Aceh' },
    { value: 'Bali', label: 'Bali' },
    { value: 'Banten', label: 'Banten' },
    { value: 'Bengkulu', label: 'Bengkulu' },
    { value: 'Gorontalo', label: 'Gorontalo' },
    { value: 'Jambi', label: 'Jambi' },
    { value: 'Jawa Barat', label: 'Jawa Barat' },
    { value: 'Jawa Tengah', label: 'Jawa Tengah' },
    { value: 'Jawa Timur', label: 'Jawa Timur' },
    { value: 'Kalimantan Barat', label: 'Kalimantan Barat' },
    { value: 'Kalimantan Selatan', label: 'Kalimantan Selatan' },
    { value: 'Kalimantan Tengah', label: 'Kalimantan Tengah' },
    { value: 'Kalimantan Timur', label: 'Kalimantan Timur' },
    { value: 'Kalimantan Utara', label: 'Kalimantan Utara' },
    { value: 'Kepulauan Riau', label: 'Kepulauan Riau' },
    { value: 'Lampung', label: 'Lampung' },
    { value: 'Maluku', label: 'Maluku' },
    { value: 'Maluku Utara', label: 'Maluku Utara' },
    { value: 'Nusa Tenggara Barat', label: 'Nusa Tenggara Barat' },
    { value: 'Nusa Tenggara Timur', label: 'Nusa Tenggara Timur' },
    { value: 'Papua', label: 'Papua' },
    { value: 'Papua Barat', label: 'Papua Barat' },
    { value: 'Riau', label: 'Riau' },
    { value: 'Sulawesi Barat', label: 'Sulawesi Barat' },
    { value: 'Sulawesi Selatan', label: 'Sulawesi Selatan' },
    { value: 'Sulawesi Tengah', label: 'Sulawesi Tengah' },
    { value: 'Sulawesi Tenggara', label: 'Sulawesi Tenggara' },
    { value: 'Sulawesi Utara', label: 'Sulawesi Utara' },
    { value: 'Sumatera Barat', label: 'Sumatera Barat' },
    { value: 'Sumatera Selatan', label: 'Sumatera Selatan' },
    { value: 'Sumatera Utara', label: 'Sumatera Utara' },
    { value: 'Yogyakarta', label: 'Yogyakarta' },
]